#include<stdio.h>
#include<signal.h>

void handler (int arg)	//this function is called by the OS and argument is also passed by the OS.
{	//SIGINT is the Argument.
	printf("CLT + c received\n");//Just works like an Intrrupt .goes back to the While loop again after Clt + c is pressed on keyboard.
}

int main()
{
	signal(SIGINT, handler);	//only registration is done. the OS only will call the function, HAPPENS During Compliation Time.
//	signal(SIGINT, NULL);	

/*	Where is SOURCE CODE STORED?
Signal source Code will be on the Kernel Side, whose behavoiur would be changed and REFLECTED on the PCB.
REFLECTED on the PCB hence The changed Functionality is applicable only when this Process is Running.

	Why is Stored ono the PCB?
Cos we are changing the Behaviour Of the signal with the help of the FUNCTION (handler) And functions are stored on the STACK SEGMENT

*/
//raise(SIGINT);	//is similar to kill(getpid, SIGINT);
//Only REGESTRATION is done i.e we are chaning the Functionality of the SIGINT To a User defined Function.
	while(1);
}
/*
emertxe@emertxe-VirtualBox:~/ecep/linuxIntervals/assignments/chapter1/signals$ ./a.out 
^CCLT + c received
^CCLT + c received
^CCLT + c received
^\Quit (core dumped)
emertxe@emertxe-VirtualBox:~/ecep/linuxIntervals/assignments/chapter1/signals$ 
*/

/*
emertxe@emertxe-VirtualBox:~/ecep/linuxIntervals/assignments/chapter1/signals$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 7066
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 7066
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited



emertxe@emertxe-VirtualBox:~/ecep/linuxIntervals/assignments/chapter1/signals$ ulimit -c 1024
emertxe@emertxe-VirtualBox:~/ecep/linuxIntervals/assignments/chapter1/signals$ ulimit -a
core file size          (blocks, -c) 1024
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 7066
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 7066
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

*/

/* final
emertxe@emertxe-VirtualBox:~/ecep/linuxIntervals/assignments/chapter1/signals$ gcc signal.c 
emertxe@emertxe-VirtualBox:~/ecep/linuxIntervals/assignments/chapter1/signals$ ./a.out 
^CCLT + c received
^\Quit (core dumped)
emertxe@emertxe-VirtualBox:~/ecep/linuxIntervals/assignments/chapter1/signals$ ls
a.out  core  signal.c
emertxe@emertxe-VirtualBox:~/ecep/linuxIntervals/assignments/chapter1/signals$ gdb Core-file core
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "i686-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Core-file: No such file or directory.
[New LWP 2519]
Core was generated by `./a.out'.
Program terminated with signal SIGQUIT, Quit.
#0  0x0804847e in ?? ()
*/
